name: Enable Buildkit Cache
description: Enables, loads, and exports the Buildkit run cache for Docker.

inputs:
  cache_dir:
    description: The directory to restore the cache.
    required: true
  cache_max_size:
    description: The maximum size of the cache.
    required: false
    default: 2g

runs:
  using: composite

  steps:
    - id: buildx
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true
        driver-opts: image=moby/buildkit:buildx-stable-1

    - name: Make Buildkit cache path
      run: |
        mkdir ${{ inputs.cache_dir }}
      shell: sh

    - name: Enable Buildkit caches
      uses: actions/cache@v3
      with:
        path: ${{ inputs.cache_dir }}/buildkit-state.tar
        key: ${{ runner.os }}-buildx-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ github.ref }}
          ${{ runner.os }}-buildx-

    - name: Load Buildkit state from cache
      uses: dashevo/gh-action-cache-buildkit-state@v1
      with:
        builder: buildx_buildkit_${{ steps.buildx.outputs.name }}0
        cache-path: ${{ inputs.cache_dir }}
        cache-max-size: ${{ inputs.cache_max_size }}
