name: Notify Slack of Failure
description: Notify a Slack channel of the workflow failure.

inputs:
  channel_id:
    description: The ID of the Slack channel to post the message.
    required: false
    default: 'github-actions'

runs:
  using: composite

  steps:
    - name: Post message
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: ${{ inputs.channel_id }}
        status: FAILED
        color: danger
