name: Chart Repo Release
concurrency:
  group: crr-${{ github.repository }}-${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      helm_version:
        description: The version of Helm to use, e.g. 3.8.1.
        required: false
        default: 3.8.1
        type: string

    secrets:
      gh_token:
        description: The GitHub token of this repository.
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: .

      - name: Configure Git
        uses: slateci/github-actions/.github/actions/configure-git@v16

      - name: Install Helm
        uses: azure/setup-helm@v3.5
        with:
          version: ${{ inputs.helm_version }}

      - name: Add dependency chart repos
        run: |
          helm repo add traefik https://helm.traefik.io/traefik

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.gh_token }}"
