name: Lint & scan image

on:
  workflow_call:
    inputs:
      file:
        description: The path to the Dockerfile.
        required: true
        type: string

jobs:
  check:
    name: Check Image
    runs-on: ubuntu-20.04

    env:
      BUILDKIT_CACHE_DIR: /tmp/buildkit-cache

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: .

      - name: Enable Buildx Cache
        uses: slateci/github-actions/.github/actions/buildkit-enable-cache@v12
        with:
          cache_dir: ${{ env.BUILDKIT_CACHE_DIR }}

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ inputs.file }}
          load: true
          target: release-stage
          push: false
          tags: app-image:${{ github.sha }}

      - name: Lint with Dockle
        uses: erzz/dockle-action@v1
        with:
          image: app-image:${{ github.sha }}
          exit-code: 1
          failure-threshold: FATAL
          timeout: "10m"

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: app-image:${{ github.sha }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          timeout: "10m"
        continue-on-error: true
