name: Lint & scan image

on:
  workflow_call:
    inputs:
      file:
        description: The path to the Dockerfile.
        required: true
        type: string

jobs:
  check:
    name: Check Image
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: .

      - name: Cache Buildx caches
        uses: actions/cache@v3
        with:
          path: /var/lib/docker/buildkit
          key: ${{ runner.os }}-buildx-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ github.ref }}
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ inputs.file }}
          load: true
          target: release-stage
          push: false
          tags: app-image:${{ github.sha }}

      - name: Lint with Dockle
        uses: erzz/dockle-action@v1
        with:
          image: app-image:${{ github.sha }}
          exit-code: 1
          failure-threshold: FATAL
          timeout: "10m"

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: app-image:${{ github.sha }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          timeout: "10m"
        continue-on-error: true
