name: Lint & scan image

on:
  workflow_call:
    inputs:
      git_ref:
        description: The branch or tag ref to check out, e.g. `refs/heads/develop`.
        required: true
        type: string
      repository:
        description: The GitHub repository to clone, e.g. 'slateci/helm-slate-api'.
        required: true
        type: string

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.git_ref }}
          path: .
          repository: ${{ inputs.repository }}

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          outputs: type=docker,dest=/tmp/image.tar
          push: false
          tags: app-image:${{ github.sha }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: image
          path: /tmp/image.tar

  lint:
    name: Dockle Lint
    runs-on: ubuntu-20.04
    needs:
      - build

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: image
          path: /tmp

      - name: Load Docker image
        run: |
          docker load --input /tmp/image.tar

      - name: Lint with Dockle
        uses: hands-lab/dockle-action@v1
        with:
          image: app-image:${{ github.sha }}
          exit-code: '0'
          exit-level: WARN

  scan:
    name: Trivy Scan
    runs-on: ubuntu-20.04
    needs:
      - build

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: image
          path: /tmp

      - name: Load Docker image
        run: |
          docker load --input /tmp/image.tar

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: app-image:${{ github.sha }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
