name: "Validate GitHub YAML"

on:
#  pull_request:
#    branches:
#      - master
  push:
    branches:
      - feature/54_switch-to-v1-tags-in-raw-script-downloads

env:
  SCHEMASTORE_BRANCHORTAG: master
  SCHEMASTORE_RAWCONTENT_URL: https://raw.githubusercontent.com/SchemaStore/schemastore

jobs:
  schema:
    name: Schema checks
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: ./checkout

      - name: Download schemas
        run: |-
          for FILENAME in github-action.json github-workflow.json
          do
          curl -fsSL ${{ env.SCHEMASTORE_RAWCONTENT_URL }}/${{ env.SCHEMASTORE_BRANCHORTAG }}/src/schemas/json/$FILENAME -o $FILENAME
          done

      - name: Validate action schemas
        uses: nrkno/yaml-schema-validator-github-action@v4
        with:
          schema: ./github-action.json
          target: ./checkout/.github/actions/gcloud-helm-setup/action.yml
