name: "Validate GitHub YAML"

on:
#  pull_request:
#    branches:
#      - master
  push:
    branches:
      - feature/54_switch-to-v1-tags-in-raw-script-downloads

env:
  SCHEMA_URL: https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/github-workflow.json

jobs:
  schema:
    name: Schema checks
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: ./checkout

      - name: Download schema
        run: |-
          curl -fsSL ${{ env.SCHEMA_URL }} -o github-workflow.json

      - name: Validate schema
        uses: nrkno/yaml-schema-validator-github-action@v4
        with:
          schema: ./github-workflow.json
          target: ./checkout/.github/**/*.yml
