name: SLATE Remote Client Release
concurrency:
  group: srcr-${{ github.repository }}

on:
  workflow_call:
    inputs:
      python_version:
        description: The version of Python to use, e.g. 3.9.
        required: false
        default: 3.9
        type: string

jobs:
  build-linux:
    name: Build Linux Client
    runs-on: ubuntu-20.04
    container: hub.opensciencegrid.org/slate/slate-client-alpine:1.1.0

    steps:
      - name: Download Shared Workflow Properties
        uses: actions/download-artifact@v3
        with:
          name: shared-workflow-props

      - name: Apply Shared Workflow Properties
        working-directory: .
        run: |-
          source workflow.properties
          echo "RELEASE_VERSION=${releaseVersion}" >> $GITHUB_ENV

      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: ./checkout
          ref: refs/tags/v${{ env.RELEASE_VERSION }}

      - name: Run CMake
        working-directory: build
        run: |-
          cmake .. -DBUILD_CLIENT=True -DBUILD_SERVER=False -DBUILD_SERVER_TESTS=False -DSTATIC_CLIENT=True

      - name: Run make
        working-directory: build
        run: |-
          export VERSION_OVERRIDE=$(echo ${{ github.ref }} | cut -d'v' -f 2)
          make

      - name: Strip symbols from binary
        working-directory: build
        run: |-
          strip slate

      - name: Create tarball
        working-directory: build
        run: |-
          tar -czvf slate-linux.tar.gz slate

      - name: Generate hash of tarball
        working-directory: build
        run: |-
          sha256sum slate-linux.tar.gz > slate-linux.sha256

      - name: Persist built binary and hash
        uses: actions/upload-artifact@v3
        with:
          name: slate-linux-artifacts
          path: |-
            build/slate-linux.tar.gz
            build/slate-linux.sha256
          retention-days: 1

  build-macos:
    name: Build MacOS Client
    runs-on: macos-12

    steps:
      - name: Download Shared Workflow Properties
        uses: actions/download-artifact@v3
        with:
          name: shared-workflow-props

      - name: Apply Shared Workflow Properties
        working-directory: .
        run: |-
          source workflow.properties
          echo "RELEASE_VERSION=${releaseVersion}" >> $GITHUB_ENV

      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: ./checkout
          ref: refs/tags/v${{ env.RELEASE_VERSION }}

      - name: Run CMake
        working-directory: build
        run: |-
          cmake .. -DBUILD_CLIENT=True -DBUILD_SERVER=False -DBUILD_SERVER_TESTS=False -DSTATIC_CLIENT=True

      - name: Run make
        working-directory: build
        run: |-
          export VERSION_OVERRIDE=$(echo ${{ github.ref }} | cut -d'v' -f 2)
          make

      - name: Strip symbols from binary
        working-directory: build
        run: |-
          strip slate

      - name: Create tarball
        working-directory: build
        run: |-
          tar -czvf slate-macos.tar.gz slate

      - name: Generate hash of tarball
        working-directory: build
        run: |-
          shasum -b -a 256 slate-macos.tar.gz > slate-macos.sha256

      - name: Persist built binary and hash
        uses: actions/upload-artifact@v3
        with:
          name: slate-macos-artifacts
          path: |
            build/slate-macos.tar.gz
            build/slate-macos.sha256
          retention-days: 1

  deploy-github:
    name: Deploy to GitHub
    runs-on: ubuntu-20.04
    needs:
      - build-linux
      - build-macos

    permissions:
      contents: write

    steps:
      - name: Download Linux Binary
        uses: actions/download-artifact@v3
        with:
          name: slate-linux-artifacts

      - name: Download MacOS Binary
        uses: actions/download-artifact@v3
        with:
          name: slate-macos-artifacts

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.tar.gz,*.sha256"
          body: |-
            See https://slateci.io/docs/tools/ for installation and usage instructions.
          name: Release ${{ github.ref_name }}
          tag: ${{ github.ref }}
          prerelease: ${{ contains(github.ref, 'pre') }}
          token: ${{ secrets.GITHUB_TOKEN }}
