name: SLATE Update Apps
concurrency:
  group: sua-${{ github.repository }}-${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      python_packages:
        description: The pip packages to use.
        required: false
        default: |
          requests==2.27.1
        type: string
      python_version:
        description: The version of Python to use, e.g. 3.9.
        required: false
        default: 3.9
        type: string

    secrets:
      slate_api_token_dev:
        description: The SLATE API token used to communicate with the development SLATE API endpoint.
        required: true
      slate_api_token_staging:
        description: The SLATE API token used to communicate with the staging SLATE API endpoint.
        required: true
      slate_api_token_prod:
        description: The SLATE API token used to communicate with the production SLATE API endpoint.
        required: true

jobs:
  notify:
    name: Notify API Servers
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - api_endpoint: https://api.dev.slateci.io
            api_token: ${{ secrets.slate_api_token_dev }}
          - api_endpoint: https://api.staging.slateci.io
            api_token: ${{ secrets.slate_api_token_staging }}
          - api_endpoint: https://api.slateci.io
            api_token: ${{ secrets.slate_api_token_prod }}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install Python packages
        uses: BSFishy/pip-action@v1
        with:
          packages: ${{ inputs.python_packages }}

      - name: Update Apps
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import requests
            
            slateAPIEndPoint = "${{ matrix.api_endpoint }}"
            slateAPIToken = "${{ matrix.slate_api_token }}"
            
            uri = f"{slateAPIEndPoint}/v1alpha3/update_apps"
            response = requests.post(
                uri,
                params={"token": slateAPIToken},
                json={"apiVersion": "v1alpha3"}
            )
            
            if response.status_code != 200:
                message = f"Unable to notify API server: {slateAPIEndPoint}"
                error(message)
                raise Exception(message)
            else:
                print(f"Successfully notified API server: {slateAPIEndPoint}")
