name: SLATE Remote Client Release
concurrency:
  group: srcr-${{ github.repository }}

on:
  workflow_call:

jobs:
  deploy-github:
    name: Deploy to GitHub
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download Shared Workflow Properties
        uses: actions/download-artifact@v4
        with:
          name: shared-workflow-props

      - name: Apply Shared Workflow Properties
        working-directory: .
        run: |-
          source workflow.properties
          echo "RELEASE_VERSION=${releaseVersion}" >> $GITHUB_ENV

      - name: Update existing GitHub Release
        uses: tubone24/update_release@v1.3.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
          TAG_NAME: "refs/tags/v${{ env.RELEASE_VERSION }}"
        with:
          prerelease: false
